name: gourmet_search_for_fenrir
description: Hot Pepper Gourmet restaurant search app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  geolocator: ^12.0.0
  http: ^1.2.1
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
